// DebuggerView.h

// Copyright (C) 2012  Miroslav Sustek <sus107@vsb.cz>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// -*- C++ -*- generated by wxGlade HG on Fri Feb  3 02:55:31 2012

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/stc/stc.h>

#ifndef DEBUGGERVIEW_H
#define DEBUGGERVIEW_H

#include "icons.h"

#include "../Debugger.h"
#include "../DebuggerListener.h"
#include "DebuggerRegistersView.h"
#include "DebuggerHexGui.h"

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include "DebuggerCodeGui.h"
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

class Debugger;
class DebuggerCodeGui;
class DebuggerHexGui;

class DebuggerView: public wxFrame, public EmulatorListener, public DebuggerListener {
public:
	// begin wxGlade: DebuggerView::ids
	enum {
		DEBUGGER_TOOL_CONTINUE = wxID_HIGHEST + 1033,
		DEBUGGER_TOOL_BREAK = wxID_HIGHEST + 1034,
		DEBUGGER_TOOL_STEP = wxID_HIGHEST + 1035
	};
	// end wxGlade

	DebuggerView(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	~DebuggerView();

	void uiUpdate();
	void emulatorEvent(EmulatorEvent event);
	void debuggerEvent(DebuggerEvent event);

private:
	// begin wxGlade: DebuggerView::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	Emulator *emulator;
	Debugger *debugger;

protected:
	// begin wxGlade: DebuggerView::attributes
	wxMenuBar* debugger_menubar;
	wxToolBar* debugger_view_toolbar;
	DebuggerCodeGui* debugger_code_view;
	DebuggerHexGui* hex_view;
	wxPanel* notebook_pane_hex;
	wxNotebook* notebook;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnDebuggerStep(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnDebuggerContinue(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnDebuggerBreak(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnViewRegisters(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnHexViewModified(wxStyledTextEvent &event); // wxGlade: <event_handler>
	virtual void OnDebuggerNotebookPageChanged(wxNotebookEvent &event); // wxGlade: <event_handler>
	void attach(Emulator *emulator, Debugger *debugger);
}; // wxGlade: end class


#endif // DEBUGGERVIEW_H
