// DebuggerCodeGui.h

// Copyright (C) 2012  Miroslav Sustek <sus107@vsb.cz>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// -*- C++ -*- generated by wxGlade HG on Sun Feb 19 19:08:09 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DEBUGGERCODEGUI_H
#define DEBUGGERCODEGUI_H

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#include <map>
#include "../Debugger.h"
#include "../EmulatorListener.h"
#include "../DebuggerListener.h"

class Debugger;
class EmulatorListener;
class DebuggerListener;

class DebuggerCodeGui: public wxPanel, public EmulatorListener, public DebuggerListener {
public:
	// begin wxGlade: DebuggerCodeGui::ids
	// end wxGlade

	DebuggerCodeGui(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
	~DebuggerCodeGui();

	void uiUpdate();
	void emulatorEvent(EmulatorEvent event);
	void debuggerEvent(DebuggerEvent event);
	void gotoAddress(int address);

private:
	// begin wxGlade: DebuggerCodeGui::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	static int parseHex(wxString in, unsigned char *out, int maxLen);

	wxMenu *rowContextMenu;
	wxMutex cellChangeMutex;

	Emulator *emulator;
	Debugger *debugger;
	std::map<int, int> addressToRowMap;
	std::map<int, int> rowToAddressMap;

	void ToggleBreakpoint(int row);

protected:
	// begin wxGlade: DebuggerCodeGui::attributes
	wxGrid* code_grid;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnSelectCell(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCodeSliderEndScroll(wxScrollEvent &event); // wxGlade: <event_handler>
	virtual void OnCellChange(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCellRightClick(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCellLeftDClick(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnContextToggleBreakpoint(wxCommandEvent &event);
	virtual void OnCodeGridSize(wxSizeEvent &event);
	void attach(Emulator *emulator, Debugger *debugger);
}; // wxGlade: end class


#endif // DEBUGGERCODEGUI_H
