// DebuggerRegistersView.h

// Copyright (C) 2012  Miroslav Sustek <sus107@vsb.cz>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// -*- C++ -*- generated by wxGlade HG on Fri Feb  3 02:49:17 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef REGISTERSVIEW_H
#define REGISTERSVIEW_H


#include "../Emulator.h"
#include "../EmulatorListener.h"
#include "../Debugger.h"
#include "../DebuggerListener.h"

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

class Debugger;

class DebuggerRegistersView: public wxFrame, public EmulatorListener, public DebuggerListener {
public:
	// begin wxGlade: DebuggerRegistersView::ids
	// end wxGlade

	DebuggerRegistersView(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	~DebuggerRegistersView();

	void uiUpdate();
	void emulatorEvent(EmulatorEvent event);
	void debuggerEvent(DebuggerEvent event);

private:
	// begin wxGlade: DebuggerRegistersView::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	Emulator *emulator;
	Debugger *debugger;

protected:
	// begin wxGlade: DebuggerRegistersView::attributes
	wxStaticText* label_af;
	wxTextCtrl* reg_af;
	wxStaticText* label_bc;
	wxTextCtrl* reg_bc;
	wxStaticText* label_de;
	wxTextCtrl* reg_de;
	wxStaticText* label_hl;
	wxTextCtrl* reg_hl;
	wxStaticText* label_pc;
	wxTextCtrl* reg_pc;
	wxStaticText* label_sp;
	wxTextCtrl* reg_sp;
	wxStaticText* label_i;
	wxTextCtrl* reg_i;
	wxStaticText* label_af2;
	wxTextCtrl* reg_af2;
	wxStaticText* label_bc2;
	wxTextCtrl* reg_bc2;
	wxStaticText* label_de2;
	wxTextCtrl* reg_de2;
	wxStaticText* label_hl2;
	wxTextCtrl* reg_hl2;
	wxStaticText* label_ix;
	wxTextCtrl* reg_ix;
	wxStaticText* label_iy;
	wxTextCtrl* reg_iy;
	wxStaticText* label_r;
	wxTextCtrl* reg_r;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnRegEnter(wxCommandEvent &event); // wxGlade: <event_handler>
    void attach(Emulator *emulator, Debugger *debugger);
}; // wxGlade: end class


#endif // REGISTERSVIEW_H
