// EmulatorView.h

// Copyright (C) 2012  Miroslav Sustek <sus107@vsb.cz>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// -*- C++ -*- generated by wxGlade HG on Tue Jan 10 21:38:21 2012

#include <wx/wx.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/rawbmp.h>
#include <wx/joystick.h>

#ifndef EMULATORVIEW_H
#define EMULATORVIEW_H

#include "../Machine.h"
#include "../Debugger.h"
#include "DebuggerView.h"

#include <map>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class EmulatorView: public wxFrame, public EmulatorListener {
public:
	// begin wxGlade: EmulatorView::ids
	enum {
		MENU_FILE_OPEN = wxID_HIGHEST + 1010,
		MENU_FILE_EXIT = wxID_HIGHEST + 1011,
		MENU_MACHINE_START = wxID_HIGHEST + 1012,
		MENU_MACHINE_STOP = wxID_HIGHEST + 1013,
		MENU_MACHINE_RESET = wxID_HIGHEST + 1014,
		MENU_MACHINE_DEBUGGER = wxID_HIGHEST + 1015,
		MENU_TAPE_OPEN = wxID_HIGHEST + 1016,
		MENU_TAPE_PLAY = wxID_HIGHEST + 1017,
		MENU_TAPE_STOP = wxID_HIGHEST + 1018,
		MENU_TAPE_REWIND = wxID_HIGHEST + 1019
	};
	// end wxGlade

	EmulatorView(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	virtual ~EmulatorView();
	void init();
	void emulatorEvent(EmulatorEvent event);

	void start();
	void stop();

private:
	// begin wxGlade: EmulatorView::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	wxFileDialog* openTapeFileDialog;
	wxFileDialog* openSnapFileDialog;

	wxTimer *timer;
	wxStopWatch *stopWatch;
#ifdef wxUSE_JOYSTICK
	wxJoystick *joystick;
	wxTimer *joystickTimer;
#endif

	Emulator *emulator;

	std::map<int, KeyboardKeys> keyboardMapping;

	uint32_t *buffer;

protected:
	// begin wxGlade: EmulatorView::attributes
	wxMenuBar* menubar;
	wxPanel* panel;
	// end wxGlade
	virtual void OnMachineStart(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineStop(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineReset(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineDebug(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeOpen(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapePlay(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeStop(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeRewind(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnFileOpen(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnFileExit(wxCommandEvent &event); // wxGlade: <event_handler>

	void OnTimer(wxTimerEvent &event);
	void OnJoystickTimer(wxTimerEvent &event);
	void OnPaint(wxPaintEvent &event);
	void OnKeyDown(wxKeyEvent &event);
	void OnKeyUp(wxKeyEvent &event);

	DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // EMULATORVIEW_H
