/* Autogenerated by png2wx.pl on Wed May  2 02:26:12 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_debug_step_into_instruction;
extern wxBitmap *_img_go_next_4;
extern wxBitmap *_img_go_next_4_small;
extern wxBitmap *_img_go_next_4x;
extern wxBitmap *_img_media_playback_pause_4;
extern wxBitmap *_img_media_playback_start_4;
extern wxBitmap *_img_stop;

#endif /* ICONS_H */
