// -*- C++ -*- generated by wxGlade HG on Sun Feb 19 19:08:09 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DEBUGGERCODEGUI_H
#define DEBUGGERCODEGUI_H

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#include <map>
#include "Debugger.h"

class Debugger;

class DebuggerCodeGui: public wxPanel {
public:
	// begin wxGlade: DebuggerCodeGui::ids
	// end wxGlade

	DebuggerCodeGui(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

	void uiUpdate();
	void gotoAddress(int address);

private:
	// begin wxGlade: DebuggerCodeGui::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	Debugger *debugger;
	int address;
	std::map<int, int> addressRowMap;

protected:
	// begin wxGlade: DebuggerCodeGui::attributes
	wxGrid* code_grid;
	wxSlider* code_slider;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnSelectCell(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCodeSliderEndScroll(wxScrollEvent &event); // wxGlade: <event_handler>
    void setDebugger(Debugger *debugger);
}; // wxGlade: end class


#endif // DEBUGGERCODEGUI_H
