// -*- C++ -*- generated by wxGlade HG on Sun Feb 19 19:08:09 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DEBUGGERCODEGUI_H
#define DEBUGGERCODEGUI_H

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#include <map>
#include "Debugger.h"

class Debugger;

class DebuggerCodeGui: public wxPanel, public DebuggerListener {
public:
	// begin wxGlade: DebuggerCodeGui::ids
	// end wxGlade

	DebuggerCodeGui(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
	~DebuggerCodeGui();

	void uiUpdate();
	void debuggerEvent(DebuggerEvent event);
	void gotoAddress(int address);

private:
	// begin wxGlade: DebuggerCodeGui::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	static int parseHex(wxString in, unsigned char *out, int maxLen);

	wxMenu *rowContextMenu;
	wxMutex cellChangeMutex;

	Debugger *debugger;
	std::map<int, int> addressToRowMap;
	std::map<int, int> rowToAddressMap;

protected:
	// begin wxGlade: DebuggerCodeGui::attributes
	wxGrid* code_grid;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnSelectCell(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCodeSliderEndScroll(wxScrollEvent &event); // wxGlade: <event_handler>
	virtual void OnCellChange(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnCellRightClick(wxGridEvent &event); // wxGlade: <event_handler>
	virtual void OnContextToggleBreakpoint(wxCommandEvent &event);
	virtual void OnCodeGridSize(wxSizeEvent &event);
    void setDebugger(Debugger *debugger);
}; // wxGlade: end class


#endif // DEBUGGERCODEGUI_H
