// -*- C++ -*- generated by wxGlade HG on Fri Feb  3 02:55:31 2012

#include "DebuggerView.h"

// begin wxGlade: ::extracode

// end wxGlade


DebuggerView::DebuggerView(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
	wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
	// begin wxGlade: DebuggerView::DebuggerView
	notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0);
	notebook_pane_hex = new wxPanel(notebook, wxID_ANY);
	notebook_pane_code = new wxPanel(notebook, wxID_ANY);
	button_step = new wxButton(this, 201, wxT("Step"));
	button_continue = new wxButton(this, 202, wxT("Continue"));
	button_break = new wxButton(this, 203, wxT("Break"));
	debugger_menubar = new wxMenuBar();
	wxMenu* wxglade_tmp_menu_1 = new wxMenu();
	wxglade_tmp_menu_1->Append(wxID_ANY, wxT("Registers"), wxEmptyString, wxITEM_NORMAL);
	debugger_menubar->Append(wxglade_tmp_menu_1, wxT("View"));
	SetMenuBar(debugger_menubar);

	set_properties();
	do_layout();
	// end wxGlade
}

void DebuggerView::setDebugger(Debugger *debugger)
{
    this->debugger = debugger;
}

BEGIN_EVENT_TABLE(DebuggerView, wxFrame)
	// begin wxGlade: DebuggerView::event_table
	EVT_BUTTON(201, DebuggerView::OnDebuggerStep)
	EVT_BUTTON(202, DebuggerView::OnDebuggerContinue)
	EVT_BUTTON(203, DebuggerView::OnDebuggerBreak)
	EVT_MENU(wxID_ANY, DebuggerView::OnViewRegisters)
	// end wxGlade
END_EVENT_TABLE();

void DebuggerView::uiUpdate()
{
	if (debugger->getEmulator()->isRunning()) {
		button_step->Disable();
		button_continue->Disable();
		button_break->Enable();
	} else {
		button_step->Enable();
		button_continue->Enable();
		button_break->Disable();
	}
}

void DebuggerView::OnDebuggerStep(wxCommandEvent &event)
{
	debugger->getEmulator()->getMachine()->stepInstruction();
	debugger->uiUpdate();
}


void DebuggerView::OnDebuggerContinue(wxCommandEvent &event)
{
	debugger->getEmulator()->start();
}


void DebuggerView::OnDebuggerBreak(wxCommandEvent &event)
{
	debugger->getEmulator()->stop();
}

void DebuggerView::OnViewRegisters(wxCommandEvent &event)
{
	debugger->uiShowRegisters();
}


// wxGlade: add DebuggerView event handlers


void DebuggerView::set_properties()
{
	// begin wxGlade: DebuggerView::set_properties
	SetTitle(wxT("Debugger"));
	// end wxGlade
}


void DebuggerView::do_layout()
{
	// begin wxGlade: DebuggerView::do_layout
	wxBoxSizer* debugger_panes = new wxBoxSizer(wxVERTICAL);
	wxBoxSizer* buttons = new wxBoxSizer(wxHORIZONTAL);
	notebook->AddPage(notebook_pane_hex, wxT("Hex"));
	notebook->AddPage(notebook_pane_code, wxT("Code"));
	debugger_panes->Add(notebook, 1, wxEXPAND, 0);
	buttons->Add(button_step, 0, wxADJUST_MINSIZE, 0);
	buttons->Add(button_continue, 0, wxADJUST_MINSIZE, 0);
	buttons->Add(button_break, 0, wxADJUST_MINSIZE, 0);
	debugger_panes->Add(buttons, 0, wxALIGN_BOTTOM|wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
	SetSizer(debugger_panes);
	debugger_panes->Fit(this);
	Layout();
	// end wxGlade
}

