// -*- C++ -*- generated by wxGlade HG on Tue Jan 10 21:38:21 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef EMULATOR_H
#define EMULATOR_H

#include "Machine.h"
#include "Debugger.h"

#include <map>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class Emulator: public wxFrame {
public:
	// begin wxGlade: Emulator::ids
	// end wxGlade

	Emulator(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	void init();

	void start();
	void stop();

	bool isRunning();
    Machine *getMachine() const;

private:
	// begin wxGlade: Emulator::methods
	void set_properties();
	void do_layout();
	// end wxGlade

	bool running;

	wxTimer *timer;
	wxStopWatch *stopWatch;

	Debugger *debugger;

	Machine *machine;
	Cpu *cpu;
	Ula *ula;
	TapeRecorder *tapeRecorder;
	Keyboard *keyboard;

	bool nmi;

	std::map<int, KeyboardKeys> keyboardMapping;

protected:
	// begin wxGlade: Emulator::attributes
	wxMenuBar* menubar;
	wxPanel* panel;
	// end wxGlade
	virtual void OnMachineStart(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineStop(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineReset(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnMachineDebug(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeOpen(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapePlay(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeStop(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTapeRewind(wxCommandEvent &event); // wxGlade: <event_handler>

	void OnTimer(wxCommandEvent &event);
	void OnPaint(wxPaintEvent &event);
	void OnKeyDown(wxKeyEvent &event);
	void OnKeyUp(wxKeyEvent &event);

	DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // EMULATOR_H
