// main.c - main source file

// Copyright (C) 2012  Miroslav Sustek <sus107@vsb.cz>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// -*- C++ -*- generated by wxGlade HG on Tue Jan 10 21:38:21 2012

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/stdpaths.h>

#include "ui/icons.h"

#include "ui/EmulatorView.h"


class Application: public wxApp {
public:
	bool OnInit();
};

IMPLEMENT_APP(Application)



void InitLanguageSupport()
{
	wxLocale* locale;
    long language = wxLANGUAGE_DEFAULT;

	// load language if possible, fall back to english otherwise
	if(wxLocale::IsAvailable(language)) {
		locale = new wxLocale( language, wxLOCALE_CONV_ENCODING );

		locale->AddCatalogLookupPathPrefix(wxT("lang"));
#ifdef __WXGTK__
		// add locale search paths
		locale->AddCatalogLookupPathPrefix(wxT("/usr"));
		locale->AddCatalogLookupPathPrefix(wxT("/usr/local"));
		wxStandardPaths* paths = (wxStandardPaths*) &wxStandardPaths::Get();
		wxString prefix = paths->GetInstallPrefix();
		locale->AddCatalogLookupPathPrefix( prefix );
#endif

		locale->AddCatalog(wxT("sus107-dt"));

		if(! locale->IsOk() ) {
			std::cerr << "selected language is wrong" << std::endl;
			delete locale;
			locale = new wxLocale( wxLANGUAGE_ENGLISH );
			language = wxLANGUAGE_ENGLISH;
		}
	} else {
		std::cout << "The selected language is not supported by your system."
		<< "Try installing support for this language." << std::endl;
		locale = new wxLocale( wxLANGUAGE_ENGLISH );
		language = wxLANGUAGE_ENGLISH;
	}

}

bool Application::OnInit()
{
	wxInitAllImageHandlers();
	InitLanguageSupport();
	initialize_images();
	EmulatorView* emulator_view = new EmulatorView(NULL, wxID_ANY, wxEmptyString);
	emulator_view->init();
	SetTopWindow(emulator_view);
	emulator_view->Show();
	return true;
}
