// -*- C++ -*- generated by wxGlade HG on Fri Feb  3 02:49:17 2012

#include "RegistersView.h"

// begin wxGlade: ::extracode

// end wxGlade


RegistersView::RegistersView(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
	wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
	// begin wxGlade: RegistersView::RegistersView
	label_af = new wxStaticText(this, wxID_ANY, wxT("AF"));
	reg_af = new wxTextCtrl(this, 101, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_bc = new wxStaticText(this, wxID_ANY, wxT("BC"));
	reg_bc = new wxTextCtrl(this, 102, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_de = new wxStaticText(this, wxID_ANY, wxT("DE"));
	reg_de = new wxTextCtrl(this, 103, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_hl = new wxStaticText(this, wxID_ANY, wxT("HL"));
	reg_hl = new wxTextCtrl(this, 104, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_pc = new wxStaticText(this, wxID_ANY, wxT("PC"));
	reg_pc = new wxTextCtrl(this, 109, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_sp = new wxStaticText(this, wxID_ANY, wxT("SP"));
	reg_sp = new wxTextCtrl(this, 110, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_i = new wxStaticText(this, wxID_ANY, wxT("I"));
	reg_i = new wxTextCtrl(this, 113, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_af2 = new wxStaticText(this, wxID_ANY, wxT("AF'"));
	reg_af2 = new wxTextCtrl(this, 105, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_bc2 = new wxStaticText(this, wxID_ANY, wxT("BC'"));
	reg_bc2 = new wxTextCtrl(this, 106, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_de2 = new wxStaticText(this, wxID_ANY, wxT("DE'"));
	reg_de2 = new wxTextCtrl(this, 107, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_hl2 = new wxStaticText(this, wxID_ANY, wxT("HL'"));
	reg_hl2 = new wxTextCtrl(this, 108, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_ix = new wxStaticText(this, wxID_ANY, wxT("IX"));
	reg_ix = new wxTextCtrl(this, 111, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_iy = new wxStaticText(this, wxID_ANY, wxT("IY"));
	reg_iy = new wxTextCtrl(this, 112, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
	label_r = new wxStaticText(this, wxID_ANY, wxT("R"));
	reg_r = new wxTextCtrl(this, 114, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);

	set_properties();
	do_layout();
	// end wxGlade
}


BEGIN_EVENT_TABLE(RegistersView, wxFrame)
	// begin wxGlade: RegistersView::event_table
	EVT_TEXT_ENTER(101, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(102, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(103, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(104, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(109, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(110, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(113, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(105, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(106, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(107, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(108, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(111, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(112, RegistersView::OnRegEnter)
	EVT_TEXT_ENTER(114, RegistersView::OnRegEnter)
	// end wxGlade
END_EVENT_TABLE();


void RegistersView::uiUpdate()
{
	wxString str;

	Cpu *cpu = debugger->getEmulator()->getMachine()->getCpu();

	reg_af->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regAF)));
	reg_bc->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regBC)));
	reg_de->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regDE)));
	reg_hl->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regHL)));

	reg_af2->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regAF_)));
	reg_bc2->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regBC_)));
	reg_de2->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regDE_)));
	reg_hl2->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regHL_)));

	reg_pc->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regPC)));
	reg_sp->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regSP)));
	reg_ix->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regIX)));
	reg_iy->ChangeValue(wxString::Format(wxT("%04x"), cpu->getRegister(regIY)));

	reg_i->ChangeValue(wxString::Format(wxT("%02x"), cpu->getRegister(regI)));
	reg_r->ChangeValue(wxString::Format(wxT("%02x"), cpu->getRegister(regR)));
}

void RegistersView::setDebugger(Debugger *debugger)
{
    this->debugger = debugger;
}

void RegistersView::OnRegEnter(wxCommandEvent &event)
{
	wxTextCtrl *textCtl = wxDynamicCast(event.GetEventObject(), wxTextCtrl);
	if (textCtl) {
		int val;
		if (sscanf(textCtl->GetValue().mb_str(), "%x", &val) == 1) {
			Cpu *cpu = debugger->getEmulator()->getMachine()->getCpu();
			switch (event.GetId()) {
				case 101: cpu->setRegister(regAF, val); break;
				case 102: cpu->setRegister(regBC, val); break;
				case 103: cpu->setRegister(regDE, val); break;
				case 104: cpu->setRegister(regHL, val); break;
				case 105: cpu->setRegister(regAF_, val); break;
				case 106: cpu->setRegister(regBC_, val); break;
				case 107: cpu->setRegister(regDE_, val); break;
				case 108: cpu->setRegister(regHL_, val); break;
				case 109: cpu->setRegister(regPC, val); break;
				case 110: cpu->setRegister(regSP, val); break;
				case 111: cpu->setRegister(regIX, val); break;
				case 112: cpu->setRegister(regIY, val); break;
				case 113: cpu->setRegister(regI, val); break;
				case 114: cpu->setRegister(regR, val); break;
			}
		}
	}
}


// wxGlade: add RegistersView event handlers


void RegistersView::set_properties()
{
	// begin wxGlade: RegistersView::set_properties
	SetTitle(wxT("Registers"));
	// end wxGlade
}

void RegistersView::do_layout()
{
	// begin wxGlade: RegistersView::do_layout
	wxBoxSizer* registers_columns = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* registers2 = new wxBoxSizer(wxVERTICAL);
	wxBoxSizer* sizer_reg_r = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_iy = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_ix = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_hl2 = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_de2 = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_bc2 = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_af2 = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* registers1 = new wxBoxSizer(wxVERTICAL);
	wxBoxSizer* sizer_reg_i = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_sp = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_pc = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_hl = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_de = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_bc = new wxBoxSizer(wxHORIZONTAL);
	wxBoxSizer* sizer_reg_af = new wxBoxSizer(wxHORIZONTAL);
	sizer_reg_af->Add(label_af, 1, wxALIGN_CENTER_VERTICAL, 0);
	sizer_reg_af->Add(reg_af, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_af, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_bc->Add(label_bc, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_bc->Add(reg_bc, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_bc, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_de->Add(label_de, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_de->Add(reg_de, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_de, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_hl->Add(label_hl, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_hl->Add(reg_hl, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_hl, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_pc->Add(label_pc, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_pc->Add(reg_pc, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_pc, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_sp->Add(label_sp, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_sp->Add(reg_sp, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_sp, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_i->Add(label_i, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_i->Add(reg_i, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers1->Add(sizer_reg_i, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	registers_columns->Add(registers1, 1, wxEXPAND, 0);
	sizer_reg_af2->Add(label_af2, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_af2->Add(reg_af2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_af2, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_bc2->Add(label_bc2, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_bc2->Add(reg_bc2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_bc2, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_de2->Add(label_de2, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_de2->Add(reg_de2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_de2, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_hl2->Add(label_hl2, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_hl2->Add(reg_hl2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_hl2, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_ix->Add(label_ix, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_ix->Add(reg_ix, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_ix, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_iy->Add(label_iy, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_iy->Add(reg_iy, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_iy, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	sizer_reg_r->Add(label_r, 1, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	sizer_reg_r->Add(reg_r, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxFIXED_MINSIZE, 0);
	registers2->Add(sizer_reg_r, 1, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
	registers_columns->Add(registers2, 1, wxEXPAND, 0);
	SetSizer(registers_columns);
	registers_columns->Fit(this);
	Layout();
	// end wxGlade
}

